#main
SCREEN_WIDTH=600
SCREEN_HEIGHT=600
GAME_TITLE ="Turtle Car Crossing Game 2023"

#Player
PLAYER_POSITION=(0,-280)
MOVE_DISTANCE=10

#scoreBoard
FONT =("Arial,sans-serif",15,'normal')
LEVEL_POSITION=(-285,270)
LEVEL_COLOR="black"
GAME_OVER_POS=(-60,0)

#car_manager
CAR_lOWER_LIMIT=-250
CAR_UPPER_LIMIT=250
CAR_MOVE_DISTANCE=5
CAR_INCREASE_SPEED=5